dask/dask-mpi

- .circleci/config.yml
- .coveragerc
- README.rst
- ci/environment-dev-2.7.yml
- ci/environment-dev-3.6.yml
- ci/install-circle.sh
- dask_mpi/cli.py
- dask_mpi/common.py
- dask_mpi/core.py
- dask_mpi/tests/test_cli.py
- setup.py
> CI improvements + Python 2.7 Compatibility

- dask_mpi/cli.py
- dask_mpi/common.py
- dask_mpi/tests/test_cli.py
@kmpaul 
Does this seem like the right approach?
**Note:** I was only able to test with `no-nanny`, as the Nannies don't seem to be forking Workers in my tests. I believe our installation of MPI allows this. But perhaps this is for another issue.
> Support scheduler-port, worker-port and nanny-port args

- dask_mpi/cli.py
- dask_mpi/tests/test_cli.py
This PR addresses the problem described in @rcthomas issue #45 
I think there was some confusion in this issue-- at NERSC our idea at the moment is to recommend that our users start Dask via the dask-mpi CLI (which never touches core.py, as far as we can tell.)
This PR implements the same logic in cli.py that already exists in core.py. It first starts the scheduler and then broadcasts the scheduler address to the workers before they can start. This behavior prevents the workers from reading an old scheduler.json file (which may have been left behind after a non-clean exit) and then hanging while they try to connect to a scheduler which does not exist.
> Add logic to broadcast current scheduler info to workers in CLI

- dask_mpi/tests/test_cli.py
This PR adds a unit test for the situation described in issue #45 and addressed in PR #46
> add stale scheduler file unit test

- dask_mpi/core.py
The WorkerType keyword argument has been changed from local_dir to local_directory. This removes a depreciation warning when launching workers.
> Update local_directory WorkerType argument. Removes deprecation warning.

- .github/workflows/tests.yml
setup-miniconda v2 fixes some deprecations in GitHub Actions. The project has also been moved to conda-incubator.
> Bump GHA setup-miniconda version

- dask_mpi/core.py
- docs/source/batch.rst
- docs/source/develop.rst
Hi @andersy005!
Here's a small docs PR about connecting to the dashboard as described in https://github.com/dask/dask/discussions/7480. (Also added `build docs` in `develop.rst`) Screenshots: 
I also updated docstring to suit method's parameters in `core.py` - if it's unnecessary I will revert it.
> Added connecting to dashboard to docs

- dask_mpi/cli.py
- dask_mpi/core.py
- dask_mpi/tests/test_cli.py
- docs/source/gpu.rst
- docs/source/index.rst
- docs/source/interactive.rst
Today `dask-mpi` has a boolean `--nanny` flag and `nanny` kwarg for CLI and interactive respecively for choosing between `Worker` and `Nanny` as the worker class.
This PR deprecates that (but doesn't remove it) and adds `--worker-class` and `worker_class` which can be used to set the class to a custom value. This came up when trying to use `dask-mpi` on GPU nodes where the class needed to be set to `dask_cuda.CUDAWorker`.
```console
$ mpirun -np 4 dask-mpi --worker-class dask_cuda.CUDAWorker
```
```python
from dask_mpi import initialize
initialize(worker_class="dask_cuda.CUDAWorker")
```
I've also added a new `--worker-options` flag which takes a JSON serialised dict and `worker_options` which takes a dict of extra kwargs to be passed to the worker class. This is important for …
> Add support for alternative worker classes and additional worker options

- dask_mpi/__init__.py
- dask_mpi/core.py
- dask_mpi/tests/core_no_exit.py
- dask_mpi/tests/test_no_exit.py
The current version of the code always uses MPI_COMM_WORLD as the communicator and calls sys.exit on some processes when the client process exits python.
This change makes it possible to use dask-mpi for part of an MPI process but then return to the original MPI workflow once it is complete. It requires the user to manually call `send_close_signal` from the client process, and to use a returned value indicating whether the process is the client or not.
> Add support for use as part of a wider MPI process

- dask_mpi/cli.py
- dask_mpi/tests/test_cli.py
This change ensures that the `--scheduler-port` flag is passed to the `Scheduler` object.
There also appears to be a test that checks this but was skipped as it was undecided whether or not the worker and nanny ports should be confiruable. For now I've removed the worker/nanny checks from the tests and removed the skip.
Closes #72.
> Reinstate scheduler port CLI option

- docs/environment.yml
Bumping the minimum docs theme to use the new version. This isn't strictly necessary but I wanted to raise a PR to trigger the rtd preview and check everything looks ok.
xref dask/dask-sphinx-theme#54
> Use new Dask docs theme

- .isort.cfg
- dask_mpi/__init__.py
- dask_mpi/core.py
- dask_mpi/tests/core_no_exit.py
This PR is designed to remove the errors that occur during shutdown during batch execution on Python 3.8.
Closes #88
> Fix shutdown errors on Python 3.8

- dask_mpi/__init__.py
- dask_mpi/core.py
- dask_mpi/tests/core_no_exit.py
I renamed the `send_close_signal` function which breaks backwards compatibility.  This changes it back.
> Rename atexit handler to not break backwards compatability

- .github/workflows/tests.yml
This is a temporary hack to allow tests to pass until #87 can be addressed properly.
> Disabling Python 3.9+ in tests (for now)

- docs/environment.yml
- docs/source/conf.py
On Monday, June 6th, dask.org will go live with a new design (see https://github.com/dask/community/issues/220). This PR is in preparation for the theme update for `dask-sphinx-theme` and can be merged in *after* https://github.com/dask/dask-sphinx-theme/pull/67 on Monday.
cc @jacobtomlinson @jsignell
> Update docs theme for rebranding

- .isort.cfg
- dask_mpi/tests/test_cli.py
While running pytest on dask_mpi, I encountered the below `fixture 'loop_in_thread' not found` error.  A quick search brought up dask/dask#9337, where they encountered the same error and fixed it with the extra imports that are in this PR.  I think this is a workaround rather than a long-term fix, but it will unstick the CI while the issue is addressed upstream.
```
(venv8) lgarrison@scclin021:~/scc/repo/dask-mpi$ pytest -xv dask_mpi/
================================================= test session starts ==================================================
platform linux -- Python 3.8.12, pytest-7.1.3, pluggy-1.0.0 -- /mnt/home/lgarrison/scc/daskdistrib/venv8/bin/python
cachedir: .pytest_cache
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/mnt/home/lgarrison/scc/repo …
```
> Fix `fixture 'loop_in_thread' not found` error in tests

- dask_mpi/__init__.py
- dask_mpi/cli.py
- dask_mpi/core.py
- dask_mpi/exceptions.py
- dask_mpi/tests/test_cli.py
- dask_mpi/tests/test_core.py
When using the CLI to start a cluster with a scheduler it assumes there will be at least two ranks, one for the scheduler and one for one or more workers. When using the `initialize` function it assumes at least three ranks, one for the scheduler, one for the client and one or more workers.
This PR adds a runtime check for this and if there aren't enough processes in the MPI Comm World it raises an exception to avoid hanging and waiting for processes that will never arrive.
```console
$ mpirun -np 1 dask-mpi        
...
--------------------------------------------------------------------------
Traceback (most recent call last):
File "/home/jtomlinson/miniconda3/envs/dask/bin/dask-mpi", line 33, in <module>
sys.exit(load_entry_point('dask-mpi', 'console_scripts', 'dask-mpi')())
File …
```
> Raise an exception if the comm world is too small

- setup.py
I noticed that when installing `dask-mpi` by itself, it does not come
with any dependencies, contrary to what `setup.py` hints at.
On a barebones cluster, I got this trying to set up a small reproducer:
```
-bash-4.2$ python3 -mvenv foobar; . ./foobar/bin/activate; pip install dask-mpi
Collecting dask-mpi
Using cached dask_mpi-2022.4.0-py3-none-any.whl (11 kB)
Installing collected packages: dask-mpi
Successfully installed dask-mpi-2022.4.0
(foobar) -bash-4.2$ pip list
Package    Version
---------- --------
dask-mpi   2022.4.0
pip        22.0.4
setuptools 47.1.0
```
It seems that the code that actually specifies the dependencies has been
commented out for a while. This PR reactivates it.
Tested with `python -mbuild -n` (no build isolation due to the YAML
dependency for `setup.py`) and …
> List dependencies correctly in distributions.

- dask_mpi/core.py
This is to ensure that if workers are launched with dask_mpi, the local_directory can be modified via dask.config('temporary_directory').
In https://github.com/dask/distributed/blob/main/distributed/core.py#L385 it assumes None default value, not "".
> Fix: Make local_directory None by default

- dask_mpi/cli.py
- docs/environment.yml
Closes #126 
Currently when running `dask-mpi` the dashboard is disabled unless you set the `--dashboard-address` flag to some value.
```bash
mpirun -np $SLURM_NTASKS dask-mpi --scheduler-file scheduler.json
mpirun -np $SLURM_NTASKS dask-mpi --scheduler-file scheduler.json --dashboard-address :8787
```
In the `dask scheduler` CLI there is a flag to enable/disable the dashboard and it defaults to enabled. This PR adds the same `--dashboard/--no-dashboard` flag to the `dask-mpi` CLI and also sets the default as enabled.
```bash
mpirun -np $SLURM_NTASKS dask-mpi --scheduler-file scheduler.json
mpirun -np $SLURM_NTASKS dask-mpi --scheduler-file scheduler.json --no-dashboard
```
> Add --dashboard/--no-dashboard flag and enable by default

- .github/workflows/release.yml
- .github/workflows/tests.yml
- readthedocs.yml
CI is currently failing for a couple of reasons, this PR fixes things up:
- The cache action version we are currently using (v2) is deprecated and is causing CI to fail in #132.
- [Readthedocs now requires the sphinx config path to be set explicitly](https://about.readthedocs.com/blog/2024/12/deprecate-config-files-without-sphinx-or-mkdocs-config/)
- Bump `actions/setup-python` to `v5` as it couldn't find Python 3.8. Also bumped release Python version to 3.10.
https://github.com/dask/dask-mpi/actions/runs/13637854290/job/38120837200?pr=132
> Fix CI failures
